import '@testing-library/jest-dom/vitest';
import { vi } from 'vitest';

// Radix UI ScrollArea uses ResizeObserver which is not available in jsdom
global.ResizeObserver = class ResizeObserver {
  observe() {}
  unobserve() {}
  disconnect() {}
};

// Mock window.electronAPI for all renderer tests
Object.defineProperty(window, 'electronAPI', {
  value: {
    ping: vi.fn().mockResolvedValue('pong'),
    createWindow: vi.fn().mockResolvedValue({}),
    killTerminal: vi.fn().mockResolvedValue(undefined),
    getTerminalStatus: vi.fn().mockResolvedValue('alive'),
    listTerminals: vi.fn().mockResolvedValue([]),
    closeWindow: vi.fn().mockResolvedValue(undefined),
    deleteWindow: vi.fn().mockResolvedValue(undefined),
    startWindow: vi.fn().mockResolvedValue({ success: true }),
    validatePath: vi.fn().mockResolvedValue(true),
    selectDirectory: vi.fn().mockResolvedValue(null),
    openFolder: vi.fn().mockResolvedValue(undefined),
    onWindowStatusChanged: vi.fn(),
    offWindowStatusChanged: vi.fn(),
    onPaneStatusChanged: vi.fn(),
    offPaneStatusChanged: vi.fn(),
    onWindowGitBranchChanged: vi.fn(),
    offWindowGitBranchChanged: vi.fn(),
    onTmuxPaneTitleChanged: vi.fn(),
    offTmuxPaneTitleChanged: vi.fn(),
    onTmuxPaneStyleChanged: vi.fn(),
    offTmuxPaneStyleChanged: vi.fn(),
    onTmuxWindowSynced: vi.fn(),
    offTmuxWindowSynced: vi.fn(),
    onTmuxWindowRemoved: vi.fn(),
    offTmuxWindowRemoved: vi.fn(),
    ptyWrite: vi.fn().mockResolvedValue(undefined),
    ptyResize: vi.fn().mockResolvedValue(undefined),
    onPtyData: vi.fn(),
    offPtyData: vi.fn(),
    splitPane: vi.fn().mockResolvedValue({ success: true }),
    closePane: vi.fn().mockResolvedValue({ success: true }),
    switchToTerminalView: vi.fn().mockResolvedValue(undefined),
    switchToUnifiedView: vi.fn().mockResolvedValue(undefined),
    onViewChanged: vi.fn(),
    offViewChanged: vi.fn(),
    getSettings: vi.fn().mockResolvedValue({ success: true, data: { language: 'zh-CN', ides: [], quickNav: { items: [] }, terminal: { useBundledConptyDll: false } } }),
    updateSettings: vi.fn().mockResolvedValue({ success: true, data: {} }),
    getSupportedIDENames: vi.fn().mockResolvedValue({ success: true, data: [] }),
    scanIDEs: vi.fn().mockResolvedValue({ success: true, data: [] }),
    deleteIDEConfig: vi.fn().mockResolvedValue({ success: true, data: [] }),
    updateIDEConfig: vi.fn().mockResolvedValue({ success: true, data: [] }),
    scanSpecificIDE: vi.fn().mockResolvedValue({ success: true, data: '' }),
    statusLineConfigure: vi.fn().mockResolvedValue({ success: true }),
    statusLineRemove: vi.fn().mockResolvedValue({ success: true }),
    saveWorkspace: vi.fn().mockResolvedValue({ success: true }),
    loadWorkspace: vi.fn().mockResolvedValue({ success: true, data: {} }),
    onWorkspaceLoaded: vi.fn(),
    offWorkspaceLoaded: vi.fn(),
    triggerAutoSave: vi.fn(),
    writeClipboardText: vi.fn().mockResolvedValue(undefined),
    readClipboardText: vi.fn().mockResolvedValue({ success: true, data: '' }),
    notifyRendererReady: vi.fn(),
    onWindowRestored: vi.fn(),
    offWindowRestored: vi.fn(),
    onWorkspaceRestoreError: vi.fn(),
    offWorkspaceRestoreError: vi.fn(),
    recoverFromBackup: vi.fn().mockResolvedValue({ success: true, data: {} }),
    onCleanupStarted: vi.fn(),
    offCleanupStarted: vi.fn(),
    onCleanupProgress: vi.fn(),
    offCleanupProgress: vi.fn(),
    openInIDE: vi.fn().mockResolvedValue({ success: true }),
    startGitWatch: vi.fn().mockResolvedValue({ success: true }),
    stopGitWatch: vi.fn().mockResolvedValue({ success: true }),
    openExternalUrl: vi.fn().mockResolvedValue({ success: true }),
    onProjectConfigUpdated: vi.fn(),
    offProjectConfigUpdated: vi.fn(),
    onClaudeModelUpdated: vi.fn(),
    offClaudeModelUpdated: vi.fn(),
  },
  writable: true,
});
